version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      prod-deps:
        dependency-type: 'production'
      dev-deps:
        dependency-type: 'development'
