import { Inter } from 'next/font/google'

import { type ReactNode } from 'react'

import { type Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'santux.dev',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang='es'>
      <body className={`${inter.className} bg-zinc-900 text-zinc-100`}>{children}</body>
    </html>
  )
}
